server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 7008

spring:
  application:
    name: user-dubbo-web
# Dubbo 配置文件
dubbo:
  application:
    name: user-web
  registry:
    address: 192.168.220.20:2181
    protocol: zookeeper