server:
  port: 9099

spring:
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/student?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456

# 日志
logging:
  level:
    com.lw.mapper: debug # 显示执行sql

#dubbo:
#  application:
#    name: block-dubbo-provider
#  registry:
#    address: 192.168.220.20:2181
#    protocol: zookeeper
#  protocol:
#    name: dubbo
#    port: 20880
#  scan:
#    base-packages: com.lw